twig:
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true

# This file is here only for symfony profiler. Profiler and it's dependencies (including twig) will not be installed in prod